# Generated by Django 4.1.2 on 2022-10-28 20:42

from django.db import migrations, models
import photos_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("album_ID", models.IntegerField()),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                (
                    "dominant_color",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "photo_url",
                    models.ImageField(
                        blank=True,
                        height_field="height",
                        null=True,
                        upload_to=photos_app.models.get_upload_path,
                        width_field="width",
                    ),
                ),
            ],
            options={
                "ordering": ["album_ID", "title"],
            },
        ),
    ]
